# Generated by Django 3.2.5 on 2021-07-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0002_auto_20210722_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='image_2',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='image_3',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='item_2',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='item_3',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='price_2',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='price_3',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
