# Generated by Django 3.2.5 on 2021-07-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0003_auto_20210722_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='image_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='image_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='item_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='item_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='price_2',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='price_3',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
