# Generated by Django 3.2.5 on 2021-07-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0005_auto_20210722_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='image_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='price_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
