# Generated by Django 3.2.5 on 2021-07-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0007_auto_20210722_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='detail',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
