# Generated by Django 3.2.5 on 2021-07-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0008_outfit_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='detail',
            field=models.CharField(blank=True, max_length=190),
        ),
    ]
