# Generated by Django 3.2.5 on 2021-07-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0010_outfit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='image',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='image_1',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='image_3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='item_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
