# Generated by Django 3.2.5 on 2021-07-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0011_auto_20210726_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='detail',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='image',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
