# Generated by Django 3.2.5 on 2021-07-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0012_auto_20210726_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='item_2',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='item_3',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='price_2',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='price_3',
        ),
        migrations.AddField(
            model_name='outfit',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
